'use strict';
const slides=[...document.querySelectorAll('.slide')];
const $=id=>document.getElementById(id);
let index=0,remaining=300,running=false,deadline=0;
function show(n){index=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.hidden=i!==index;s.classList.toggle('active',i===index)});document.body.classList.toggle('is-dark',slides[index].classList.contains('dark'));$('counter').textContent=String(index+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');$('slide-label').textContent=slides[index].dataset.label;$('prev').disabled=index===0;$('next').disabled=index===slides.length-1;$('progress-fill').style.width=((index+1)/slides.length*100)+'%';const [timing,...script]=(window.talkNotes?.[index]||'').split('\n');$('timing').textContent=timing;$('script').textContent=script.join('\n').trim();history.replaceState(null,'','#'+(index+1));document.title=`${index+1}. ${slides[index].dataset.label} — What's On Korea`;}
function fromHash(){const n=Number(location.hash.slice(1));show(Number.isInteger(n)&&n>=1?n-1:0)}
function notes(open=$('notes').hidden){$('notes').hidden=!open;$('notes-toggle').setAttribute('aria-expanded',String(open))}
function renderTimer(){const seconds=running?Math.max(0,Math.ceil((deadline-Date.now())/1000)):remaining;if(seconds===0){remaining=0;running=false}$('timer').innerHTML=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')+' <span>'+(running?'일시정지':seconds===0?'종료':remaining===300?'시작':'계속')+'</span>';$('timer').classList.toggle('expired',seconds===0)}
function toggleTimer(){if(running){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));running=false}else if(remaining>0){deadline=Date.now()+remaining*1000;running=true}renderTimer()}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('fullscreen').textContent='브라우저 전체화면 사용'}}
$('prev').onclick=()=>show(index-1);$('next').onclick=()=>show(index+1);$('timer').onclick=toggleTimer;$('reset').onclick=()=>{remaining=300;running=false;renderTimer()};$('notes-toggle').onclick=()=>notes();$('notes-close').onclick=()=>notes(false);$('fullscreen').onclick=fullscreen;$('help').onclick=()=>$('help-dialog').showModal();$('help-close').onclick=()=>$('help-dialog').close();
window.addEventListener('hashchange',fromHash);
window.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if($('help-dialog').open||$('image-dialog').open)return;if(e.target.closest('button')&&[' ','Enter'].includes(e.key))return;switch(e.key){case 'ArrowRight':case 'PageDown':case ' ':e.preventDefault();show(index+1);break;case 'ArrowLeft':case 'PageUp':e.preventDefault();show(index-1);break;case 'Home':e.preventDefault();show(0);break;case 'End':e.preventDefault();show(slides.length-1);break;case 'n':case 'N':notes();break;case 'f':case 'F':fullscreen();break;case 't':case 'T':toggleTimer();break;case 'r':case 'R':$('reset').click();break;case 'Escape':notes(false);break;case '?':$('help-dialog').showModal();}});
let touch=null;$('deck').addEventListener('touchstart',e=>{touch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});$('deck').addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)show(index+(dx<0?1:-1));touch=null},{passive:true});
setInterval(renderTimer,250);fromHash();renderTimer();

for(const button of document.querySelectorAll('[data-image]')){button.addEventListener('click',()=>{const original=button.querySelector('img');$('expanded-image').src=button.dataset.image;$('expanded-image').alt=original.alt;$('image-description').textContent=original.alt;$('image-dialog').showModal()})}
$('image-close').onclick=()=>$('image-dialog').close();
